### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Sirenamogus** [Goldorion/File-Manager-MCreator#10]
I have everything set up exactly how it is in the example image but it just won't work. 
it creates the file, but it doesn't write anything in it like it's supposed to.
![image](https://user-images.githubusercontent.com/82350957/126034830-df4c139d-be57-4c9c-bf26-a4082b1ebac4.png)
been trying at it for hours to try and make it work but it just won't, and there is very little documentation on the plugin

**Comment by Sirenamogus** [comment]
I managed to get more information on the problem.
so when I have the "write to file" block anywhere on the procedure, be it inside the "write following lines inside" block or just on their own, it causes some kind of build error. but the build error seems to be silent, it doesn't give me any apparently visible build error but it otherwise acts as a build error  (refuses to save my changes if I have the block, but shows no indication of failure to save)

example:
procedure:
send message to all players: TEST
result:
works as intended.

procedure:
same procedure, change message from 'TEST' to 'LIGMA' and add the "write to file" block
result:
continues to give message "TEST"

procedure:
same procedure, message: LIGMA, "write text to file" block is now inside of a "write following lines inside" block.
result: 
continues to give message "TEST"

procedure:
same procedure but the "write to file" block is removed.
result:
gives message: "LIGMA"

**Comment by Goldorion** [comment]
You are checking if the file exists before giving it a value. I know the image in the description shows this, but it is an error of mine.
