### ISSUE TITLE
Trigger Restrictions/Exceptions when using existing triggers

### ISSUE THREAD

**Issue by smmmadden** [Goldorion/File-Manager-MCreator#11]
Hi Goldorion,
Excellent plugin option for MCreator 2021-2.  Thank you very much for creating this long desired plugin!!!  I have use cases that I want to use this for and at looks like we're on track to getting there soon, but I am seeing an issue with v4 and MCreator 2021-2 release. 
**Background**
**Use Case 1:** Create a welcome message based on userID (display name), save in config.json file and allow admins to add their own.  Enh: Support color, size and screen location
**Use Case 2:** Create a config file to hold default settings for mod. This includes enabling or disabling blocks, items, armor and other features with true/false logic on each. This would allow administrator to choose exactly what features they want enabled on their server and what they do not (due to personal choice or conflicts with other mods).
**Use Case 3:** Check for existence of config file and last update date and update with new settings only (preserving previous setup). Allows for updating with new features but maintaining old settings (unless included for other reasons that require a change).
**Use Case 4:** Write to logfile when the mod was initialized, log warnings or errors and completed, giving assurance everything was loaded properly
**Use Case 5:** Provide edit config settings through Client "Mods" UI

There does appear to be restrictions on which trigger can be used with the FileUtil calls.  While I can duplicate the above for JSON, the TEXT example never writes out a file (bug?).  The JSON examples check for A block broken trigger and it does write the file out and display to the end user part of the content.  I cannot seem to get the yourname variable to display the value for one using MCreator client and client-server.  Perhaps an issue with where the files are written in current workspace\run folder or there is more I need in the element?
The issue with the triggers (that I'm seeing anyway), have to do with already using a trigger previously and then there is a conflict instead of invoking both triggers sequentially or consecutive. It throws an exception about trying to trigger it (even though it does appear to work). It is the same [exception](https://pastebin.com/5FaaCD1E) using client and client-server during execution of trigger.  
**Element Details:** 
![image](https://user-images.githubusercontent.com/10309346/134921926-12861536-09ae-4161-8b6b-347abc518884.png)

**File Contents**   MCreator-2021-2/Workspace/ores/run/oresconfig.json 
![image](https://user-images.githubusercontent.com/10309346/134921767-47f82ec8-9ab2-4c3f-be7b-2c92cb4f6d66.png)
Do let me know if you need anything further to analyze.
Thanks in advance! --Steve

**Comment by Goldorion** [comment]
Your code doesn't work because you don't give a value to your File variable. When you check if your file exists, you are checking nothing, so it always returns false.

**Comment by smmmadden** [comment]
I turned on debugging as seen below and there isn't an option to set the filename before checking for it, so it is throwing an exception for FileNotFound even though it is there.
![image](https://user-images.githubusercontent.com/10309346/135292955-9cec7232-72f2-49f5-bcd8-0ddede9f108b.png)
Here is the image of the procedure with debug lines.  I could not locate an element for Set Local: myFile to a [filename].  The set/gets are purple, but no purple element that goes with the set/gets.  The read JSON file doesn't recognize oresconfig as the json filename.  Even in the screenshot examples provided, it couldn't work without first setting the filename, so not sure how you even got it working for reading.  Writing works perfectly.
![image](https://user-images.githubusercontent.com/10309346/135299444-a853b02f-1173-4a6e-9466-e74c6777796d.png)
![image](https://user-images.githubusercontent.com/10309346/135299526-27628513-69de-4dc0-847b-9f30b7974363.png)
Ideally, if using FileManager just include the field for the Set Local: myFile name in the shape if no other element can be used to set the value.

**Comment by smmmadden** [comment]
I managed to rewrite the procedure and got the filename set but only by editing the Java to explicitly set the value for myFile seen below.  For anyone else wanting to do something similar, you may need to do the same thing as I couldn't get Global Variables to work with the FileManager plugin either.
![image](https://user-images.githubusercontent.com/10309346/135787437-f7a062a9-c859-4187-bef4-fdd90b365261.png)
Once you edit the code, you cannot lock it again or the changes would be lost.
![image](https://user-images.githubusercontent.com/10309346/135787589-2d5eb3bc-740f-418b-a2f8-ef0bc4e80af0.png)
Here is the written file which the procedure will now verify if the enable_welcome is set to true, the welcome_message will be displayed to the player.  Just something very simple that I'll be expanding on for many other properties.  Hope this helps others until the real solution for setting the filename can be made without editing code. :-)
