### ISSUE TITLE
Idea: Expand variable scope or read file on file name

### ISSUE THREAD

**Issue by Cubyc1** [Goldorion/File-Manager-MCreator#15]
#### **What do I mean?**
As of now it's, rightfully so, only possible to create a global variable on an individual Java session (_GLOBAL_SESSION_ scope). This has a good amount of implementations, but in my opinion not for a real '_config_'. This is because the config file will always be overwritten with the new file of a new session. Whatever you've configured will be lost. 

Whenever you create a config file in a certain session, renaming another file to e.g. '_config.json_', it will correctly switch over to the newer renamed file. But if you choose to not create a new file in a new session (e.g. because it already exists) with the same file name and global variable, while also keeping the original config from the previous session, this does not work. Even if you keep the original file and do not replace it, the new global variable in your newer session will not point to that 'old' file, if a new file isn't created with the same name. In turn, the config will always be overwritten.

#### **Possible solution**
First I want to clarify that I am by no means familiar with all the constraints and/or restrictions of the Java code of Minecraft. But wouldn't it be possible to define a global file variable to the _GLOBAL_MAP_ or _GLOBAL_WORLD_ scope to at least save the contents of e.g. a config? Or might it be possible to directly read out a file in a directory on the file name?

I think for most of the MCreator mods out there, including my own, require the player to simply play Minecraft. So even if a global variable is bound to the _GLOBAL_MAP_ scope, it does not matter, because I will always have to join a world/map.

See added workspace for one of my current example implementations:
[config_file_example.zip](https://github.com/Goldorion/File-Manager-MCreator/files/7463660/config_file_example.zip)
(Create and/or join a world to create the config directory and file)

_(MCreator version 2021.2 snapshot 33614)_

**Comment by Goldorion** [comment]
The problem of overwritten files has been fixed with a91eb6229b0ed4c9bd27fd6a3bfde942e2993f03
