### ISSUE TITLE
Cant write to file | only able to create files

### ISSUE THREAD

**Issue by DeadTrapsDevelopment** [Goldorion/File-Manager-MCreator#16]
Hello 
im only able to create files with File Manager but if i try write things in the files i get a silent error with 
https://pastebin.com/reAnj4Hb

If i do it like your example picture in the plugin description it wont work.
if i remove the write part it works.
it wont generate or change the code of the class with the write parts.

Already tested the latest build of file manager and one version lower too and also installed all snapshots of mcreator for 1.16.5 to test it with all versions.
Also builded the file manager with gradle on my own to test if uploaded version is maybe broken but nothing help.

Same error everytime.

What im doing wrong xD

**Comment by Goldorion** [comment]
Nothing, I forgot to update the template file when I changed the field for the variable name to an input field xD

**Comment by DeadTrapsDevelopment** [comment]
> Nothing, I forgot to update the template file when I changed the field for the variable name to an input field xD
oh ok xD
no idea how to work with the template files.
what i need to change ?

**Comment by Goldorion** [comment]
For each generator you want to use, open the following file `generatorFolder/procedures/write_line.java.ftl`. Then, change `field$var` by `input$var`. Then save the file. However, I'm working on a patch (or an update depending on if I succeed to make something) and I will fix it.

**Comment by DeadTrapsDevelopment** [comment]
Sorry for reopening this issue xD
Downloaded the new Version and now i was thinking it works but if i write to file it creates a wrong symbol
ModnameModVariables.varnamebw.write("test");
it adds bw.write("test")
so i get everytime the build error

error: cannot find symbol 
               ModnameModVariables.varnamebw.write("test"); 
                                          ^ 
  symbol:   variable varnamebw
  location: class de.tarantel.modname.ModnameModVariables

**Comment by DeadTrapsDevelopment** [comment]
> For each generator you want to use, open the following file `generatorFolder/procedures/write_line.java.ftl`. Then, change `field$var` by `input$var`. Then save the file. However, I'm working on a patch (or an update depending on if I succeed to make something) and I will fix it.

Sorry for reopening this issue xD
Downloaded the new Version and now i was thinking it works but if i write to file it creates a wrong symbol
ModnameModVariables.varnamebw.write("test");
it adds bw.write("test")
so i get everytime the build error

error: cannot find symbol 
               ModnameModVariables.varnamebw.write("test"); 
                                          ^ 
  symbol:   variable varnamebw
  location: class de.tarantel.modname.ModnameModVariables

**Comment by DeadTrapsDevelopment** [comment]
> For each generator you want to use, open the following file `generatorFolder/procedures/write_line.java.ftl`. Then, change `field$var` by `input$var`. Then save the file. However, I'm working on a patch (or an update depending on if I succeed to make something) and I will fix it.

Sorry for reopening this issue xD
Downloaded the new Version and now i was thinking it works but if i write to file it creates a wrong symbol
ModnameModVariables.varnamebw.write("test");
it adds bw.write("test")
so i get everytime the build error

error: cannot find symbol
ModnameModVariables.varnamebw.write("test");
^
symbol: variable varnamebw
location: class de.tarantel.modname.ModnameModVariables
