### ISSUE TITLE
Still cant write also with new version ^^

### ISSUE THREAD

**Issue by DeadTrapsDevelopment** [Goldorion/File-Manager-MCreator#17]
Sorry for reopening this issue xD
Downloaded the new Version and now i was thinking it works but if i write to file it creates a wrong symbol
ModnameModVariables.varnamebw.write("test");
it adds bw.write("test")
so i get everytime the build error

error: cannot find symbol
ModnameModVariables.varnamebw.write("test");
^
symbol: variable varnamebw
location: class de.tarantel.modname.ModnameModVariables

**Comment by Goldorion** [comment]
The version I uploaded wasn't the good one. Simply re-download it.
