### ISSUE TITLE
File Manager 5.0 - not working with MCreator 20213 build

### ISSUE THREAD

**Issue by smmmadden** [Goldorion/File-Manager-MCreator#21]
Just installed the latest MCreator (20213) and v5 of FileManager.  Unfortunately, I'm not able to open my procedure block and it is not creating/reading the json file.  Opening the procedure shows no content with these two errors at the bottom.
![image](https://user-images.githubusercontent.com/10309346/146299689-f5f2b9d0-6839-4782-bf1c-c7084169ef17.png)
Tried to lock the procedure code and look at the java but I'm not able to even open it that way either. :-( 
Tried with the 49312 build to see if it is MCreator or FileManager but I couldn't get the plugin to load or show up in the list (even putting it there manually and restarting MCreator).
The latest MCreator does find it, is registered and loaded.
![image](https://user-images.githubusercontent.com/10309346/146300670-1980b453-4803-434f-96cb-fe8d2df091bf.png)
Any ideas on how to get past it?  Thanks!

**Comment by Goldorion** [comment]
Old workspaces are not compatible. Read thr changelog

**Comment by smmmadden** [comment]
sorry I missed that changelog.  I see it now and sad I have to rebuild it over again.  :-(
