### ISSUE TITLE
Copy path doesn't seem to want to actually download anything.

### ISSUE THREAD

**Issue by mcwoodcraft** [Goldorion/File-Manager-MCreator#25]
### Issue description

It seems like the Copy path block does nothing really, it's not adding or removing any text or anything to the specified location. Unless I have misunderstood what that block does or if I might have done something incorrectly.

### How to reproduce this issue?

Step 1: Setup a simple read/write system.
Step 2: Insert the Copy path block into the write system.

### Operating system

Windows

### Details

Newest MCreator/Plugin
Forge 1.16.5

### Example workspace

Can provide if needed.

### Logs

Can provide if needed.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Please provide a minimal reproducible workspace...

**Comment by mcwoodcraft** [comment]
Well as I said II might have misunderstood what the block does but shouldn't it create something with this procedure?
[download.zip](https://github.com/Goldorion/File-Manager-MCreator/files/8790448/download.zip)

**Comment by mcwoodcraft** [comment]
As it's only 1 procedure, I can include a screenshot in case the issue is obvious.
![image](https://user-images.githubusercontent.com/94686352/170809279-8644f269-59e2-4a03-9c11-5ff15aa7cb01.png)

**Comment by Goldorion** [comment]
This is not a valid file.

**Comment by mcwoodcraft** [comment]
I see, sorry about that. You know having documentation or a Wiki going indepth about the different blocks would do wonders when working with it.
