### ISSUE TITLE
return block dont work 

### ISSUE THREAD

**Issue by spacemex** [Goldorion/File-Manager-MCreator#26]
### Issue description

Can Not use return blocks in side the "Reas JSON file and get values"

### How to reproduce this issue?

error is can not use return blocks in  statement blocks

### Operating system

Windows

### Details

plugin version 5.3
mcreator version 2022.1
forge version is 1.18.2

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
This is normal. It is an MCreator check to avoid problems.
