### ISSUE TITLE
Blockstate support

### ISSUE THREAD

**Issue by northwesttreesgaming** [Goldorion/File-Manager-MCreator#27]
### Feature description

Support read and convert into a blockstate.
It might be possible to do so via a string to block state variables but a converter would be needed.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my feature request <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already suggested</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Electrofried** [comment]
This would be so helpful.
I am trying to import a user editable list of blocks as you can see in the attached picture and this is probably exactly the feature I need.

![mcreatorHOW](https://user-images.githubusercontent.com/27886155/200180043-138260b6-e524-4d5f-852e-9defded07412.png)
