### ISSUE TITLE
New procedures for json

### ISSUE THREAD

**Issue by ddemile** [Goldorion/File-Manager-MCreator#28]
### Feature description

New procedures for parsing json strings and stringifying json objects

Likes that :
![Sans titre](https://user-images.githubusercontent.com/104416229/203312543-b4c77766-ac5f-4441-8d11-1546c86b46fc.png)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my feature request <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already suggested</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
If you are the author of the plugin, you ahould open a PR to add them into the plugin directly, so you will get the credit for them.
