### ISSUE TITLE
Get World Directory Block, and Interate thru datapack

### ISSUE THREAD

**Issue by Vexxen1** [Goldorion/File-Manager-MCreator#32]
### Feature description

It would be nice if we could get the world directory, so we can grab and use datapack files. As well as if you want to go further, have a block that will itorate thru all the datapacks in the world, so we can use json within a datapack to generate things with are mod. 

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my feature request <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already suggested</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by X66Herobrine66X** [comment]
Agreed, I really want to be able to make world specific data files.
