### ISSUE TITLE
5.6 Blocks Not Appearing 

### ISSUE THREAD

**Issue by GalaxyGaming2OOO** [Goldorion/File-Manager-MCreator#33]
### Issue description

so today I downloaded and install version 5.6 to find that the move/copy blocks are not in file manager
I tried reinstalling the plugin several times but it still doesn't work 
I do see the blocks when looking into the plugin code
but they don't come up in app

### How to reproduce this issue?

launch mcreator
click file manager
No Blocks to be found

### Operating system

Windows

### Details

Plugin Version 5.6
MCreator version: 2022.3

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
They do 
![image](https://user-images.githubusercontent.com/38427877/208695114-628b96fd-066c-4814-9d11-8dbdb7a80351.png)

**Comment by GalaxyGaming2OOO** [comment]
i found the issue for some reason the 5.5 verison is still there after deleting it idk why do you know how to fix this???
