### ISSUE TITLE
"Write [X] in the file [Y] and add a new line [true]" does not write a new line

### ISSUE THREAD

**Issue by swelkinnn** [Goldorion/File-Manager-MCreator#44]
### Issue description

Fairly self explanatory, but with version 5.6.3 and on 2023.2 EAP 20712, the block in question does not create a new line regardless of the true or false at the end. 

The sample workspace has 2 procedures to write a file saying "line 1" "line 2" and "line 3" both with and without adding new lines. Both of these files provide the same output, being "line 1line 2line 3"

### How to reproduce this issue?

1) Create a procedure using the block, and set the add a new line section to true
2) Open file it creates

### Operating system

Windows

### Details

Plugin version 5.6.3
MCreator 2023.2 EAP 20712
Tested with 1.19.2 and 1.19.4 generators 

### Example workspace

[filemanager_newline_sample.zip](https://github.com/Goldorion/File-Manager-MCreator/files/11579130/filemanager_newline_sample.zip)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
I literally found this bug 1 hour ago. It will be fixed in the next update!
