### ISSUE TITLE
newLine doesn't work

### ISSUE THREAD

**Issue by JohnMcMichael2** [Goldorion/File-Manager-MCreator#46]
### Issue description

Setting a write lines into txt file block to create a new line doesn't work, the "bw.newLine();" method isn't placed in the code, meaning the line break never occurs when writing into files.
![image](https://github.com/Goldorion/File-Manager-MCreator/assets/134332638/649b7a28-a71f-4877-bc02-e4ee626f300b)
![image](https://github.com/Goldorion/File-Manager-MCreator/assets/134332638/bf4db309-7b42-4ec8-b59b-81b3423290e7)

### How to reproduce this issue?

Write lines into a txt file and set newLine to "true", then check the file 

### Operating system

Windows

### Details

Plugin version: 5.7

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
What generator do you use? It should be fixedz so I might forgot one.

**Comment by JohnMcMichael2** [comment]
I was using 1.18.2 changed to 1.16.5, but I doubted that would cause any problems since what I was doing didn't involve any Minecraft-specific functions. 

I was able to fix it by doing this:

Change write_line.java.ftl from
`{
	${field$VAR?replace("local:", "")?replace("global:", "")}bw.write(${input$text});
	<#if input$newLine == "true">
	    ${field$VAR?replace("local:", "")?replace("global:", "")}bw.newLine();
	</#if>
}`
to
`{
	${field$VAR?replace("local:", "")?replace("global:", "")}bw.write(${input$text});
	<#if input$newLine == "(true)">
	    ${field$VAR?replace("local:", "")?replace("global:", "")}bw.newLine();
	</#if>
}`

The missing parenthesis seemed to be the problem. All generators in the current version lack the parenthesis too. All generators on the last version supporting 1.16.5 DO have them, including on the 1.18 and 1.19 ones.

**Comment by Goldorion** [comment]
YOu don't use the correct version of File Manager because the fix is already applied to Forge 1.18.2 
![image](https://github.com/Goldorion/File-Manager-MCreator/assets/38427877/d2ed2aef-582e-4cee-b34b-4bf6dade9296)

Also, the fact you use File Manager says you are still on an old version because I dropped support for it a while ago.

**Comment by JohnMcMichael2** [comment]
Ah then I can't complain about this lol. Curious why the parenthesis being missing stops it from working in older versions but is unneeded now.

**Comment by Goldorion** [comment]
> Curious why the parenthesis being missing stops it from working in older versions but is unneeded now.

SomeoneElse made several optimizations to the generated code, like removing useless parenthesis and like I'm checking the generated of the logic block, meaning the condition wasn't true anymore
