### ISSUE TITLE
Write to Text and Json Overides each other

### ISSUE THREAD

**Issue by Dente222** [Goldorion/File-Manager-MCreator#5]
Yep if you try to write a single line as text then try to add Json value it will gonna end up like this

whatever you have written with the Text file PB
}

and when you do the opposite then the Text file will be ignored leaving only Json line

also adding naming for Json file would make it more clear

**Comment by Goldorion** [comment]
I am not sure to understand. Can you give more details or steps to reproduce the bug, please?

**Comment by Dente222** [comment]
This is how config file looks like when you try to add description to anything
[https://i.imgur.com/jXtNYPV.png](url)

This is how it looks when you try to add json value into description text file
[https://i.imgur.com/OsbeVDu.png](url)

Basically, you cant add Descriptions when using Write to Json, write to text overrides that
we can talk about that over discord if you want, will be easier I think

**Comment by Goldorion** [comment]
I did not design the two file writers to work together, so it is the normal behaviour of the blocks. I can check if I can add a comment block for the JSON files, but I am not sure if this is possible.

**Comment by Dente222** [comment]
thing is that this is a bit pointless if you cant add a description :L

**Comment by Goldorion** [comment]
> 
> 
> thing is that this is a bit pointless if you cant add a description :L

Usually, the name of the variable says what it is.

**Comment by Dente222** [comment]
> > thing is that this is a bit pointless if you cant add a description :L
> 
> Usually, the name of the variable says what it is.
> Edit: When you can't explain with the name of the variable, you create a documentation.

true but I was thinking of making something more like this
`beekeeping {
    # If true, the last item produced by a queen bee will be another queen bee. [default: true]
    B:apiarylastresultequalsQueen=true

    # The higher the value, the more beehives are generated. [range: 0 ~ 32767, default: 10]
    I:beehiveRarity=10

    # Enable generation of beehives. [default: true]
    B:enableBeehiveGeneration=true

    # Allows grubs and cooked grubs to be used in listAllrawmeat and listAllcookedmeat. [default: true]
    B:enablebeegrubaslistAllmeat=true
}
`
