### ISSUE TITLE
Remove JSON property

### ISSUE THREAD

**Issue by QWXL** [Goldorion/File-Manager-MCreator#51]
### Feature description

How do I remove (unset) a Json property?
If you haven't added this feature or block, please do so.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my feature request <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already suggested</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Gat0Dev** [comment]
Bump
