### ISSUE TITLE
Just doesn't load

### ISSUE THREAD

**Issue by KilaxYT** [Goldorion/File-Manager-MCreator#53]
### Issue description

It honestly just doesn't load. Does it have to be a new workspace or something?

### How to reproduce this issue?

You probably can't reproduce this.

Load the plugin.

### Operating system

Windows

### Details

V.5.7
2023.2
fabric-1.20.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
That's not the right plugin.
