### ISSUE TITLE
Get client directory

### ISSUE THREAD

**Issue by QWXL** [Goldorion/File-Manager-MCreator#54]
### Feature description

I'm trying to add files to the player's client, but when I use "Get Game Directory" or "Get Temporary Directory", the location is always on the server.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my feature request <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already suggested</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Added by https://github.com/Goldorion/File-Manager-MCreator/commit/d359ff6e2a8c1cd0bbd8e0d7e13e0a788d09f93a
