### ISSUE TITLE
Procedure loses start block

### ISSUE THREAD

**Issue by Seshua** [Goldorion/File-Manager-MCreator#6]
Mcreator version: 2020.5
MC Version 1.15.2
Filemanager version 3.0

After saving/exiting the procedure all its contents and the start block are gone.

The procedure itself only contains creating a directory for my config, creating the config itself, and adding one json property, with a player_persistant global variable.

Mcreator.log --> https://pastebin.com/tKu6swaX

**Comment by Goldorion** [comment]
Everything works perfectly for me. Make sure to use the same version of the plugin or to use a version of MCreator supported by the plugin.
