### ISSUE TITLE
Procedure not recognizing string properties for Add JSON property

### ISSUE THREAD

**Issue by smmmadden** [Goldorion/File-Manager-MCreator#60]
### Issue description

I've added a string variable and trying to add the shape for Add JSON property to set it in the configuration file.  I only see one entry and not the string.  Tried JSON Object as well with no luck and closing MCreator and re-opening space.

### How to reproduce this issue?

![image](https://github.com/Goldorion/File-Manager-MCreator/assets/10309346/28e34037-914c-40d4-b1b8-9c64b138b42e)

### Operating system

Windows

### Details

Plugin Version: 5.8
MCreator Version 2023.4
Forge: 1.20.1

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
It's `Add thePropertyName to jsonObjectVariable and setValueTo theValueYouWant`
