### ISSUE TITLE
Neoforge 1.20.4 - Compilation Errors 

### ISSUE THREAD

**Issue by smmmadden** [Goldorion/File-Manager-MCreator#61]
### Issue description

getting compilation errors with the latest version of today. I've even removed the shapes and re-added them and same errors (Neoforge 1.20.4).
symbol: class Gson
location: class CmdSetHomeProcedure
C:\MCreator-Releases\MCreator20241\workspaces\serverbasics\src\main\java\net\mcreator\tmtmcserverbasics\procedures\CmdSpeedUp2Procedure.java:39: error: cannot find symbol
mainConfigRO = new Gson().fromJson(jsonstringbuilder.toString(), com.google.gson.JsonObject.class);
^
is it not finding the variables in the procedures?

### How to reproduce this issue?

Existing Workspace from Forge 1.20.1 using MCreator 2023.4 and FileManager 5.8
Built Workspace and had compilation errors on procedures
Removed existing shapes and re-added and had same compilation errors
![image](https://github.com/Goldorion/File-Manager-MCreator/assets/10309346/103a444a-63d1-4907-9bf7-dc35acc6cfca)

### Operating system

Windows

### Details

Plugin Version: 5.9
MCreator: 2024.1
NeoForge: 1.20.4

### Logs

![image](https://github.com/Goldorion/File-Manager-MCreator/assets/10309346/30f06ab7-3ede-4545-ad54-26342c8cc92e)
on all procedures that read or create the configuration file.

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
For the moment, lock your code and replace `new Gson()` with `new com.google.gson.Gson()`. That's not ideal, but that's the only solution (and the solution I'll need to use)

**Comment by smmmadden** [comment]
Thanks for the quick reply.  I'll give that a go and yeah, not ideal since I have to do it to about 40 procedures in this one mod. :-(  Will let you know once I've done it.

**Comment by smmmadden** [comment]
Made the changes and found one more change needed.  The initial procedure that creates the json file for the mod.
[C:\MCreator-Releases\MCreator20241\workspaces\serverbasics\src\main\java\net\mcreator\tmtmcserverbasics\procedures\CreateSimpleConfigProcedure.java:81](file:///C:/MCreator-Releases/MCreator20241/workspaces/serverbasics/src/main/java/net/mcreator/tmtmcserverbasics/procedures/CreateSimpleConfigProcedure.java:81): error: cannot find symbol 
                Gson mainGSONBuilderVariable = new GsonBuilder().setPrettyPrinting().create(); 
                ^ 
  symbol:   class Gson 
  location: class CreateSimpleConfigProcedure 
[C:\MCreator-Releases\MCreator20241\workspaces\serverbasics\src\main\java\net\mcreator\tmtmcserverbasics\procedures\CreateSimpleConfigProcedure.java:81](file:///C:/MCreator-Releases/MCreator20241/workspaces/serverbasics/src/main/java/net/mcreator/tmtmcserverbasics/procedures/CreateSimpleConfigProcedure.java:81): error: cannot find symbol 
                Gson **mainGSONBuilderVariable** = new GsonBuilder().setPrettyPrinting().create(); 
                                                   ^
All the other procedures after rebuilding the code compiled successfully.  Not able to test it yet until this last procedure that creates the file works. :-)

**Comment by Goldorion** [comment]
That's the same thing. Just replace all Gson by com.google.gson.Gson

**Comment by smmmadden** [comment]
tried that and new com.google.gson.Gson.GsonBuilder() and it flagged it as invalid.
![image](https://github.com/Goldorion/File-Manager-MCreator/assets/10309346/77c2a54a-0f7d-42e1-b5b6-1f1c78afea5d)
![image](https://github.com/Goldorion/File-Manager-MCreator/assets/10309346/30922e2e-fa32-41ce-b04a-dc2c2431d325)

**Comment by smmmadden** [comment]
Here is the procedure if it helps debug further
[CreateSimpleConfig.zip](https://github.com/Goldorion/File-Manager-MCreator/files/14940720/CreateSimpleConfig.zip)

**Comment by Goldorion** [comment]
Ok, I'll do my own tests once I have more free time. It'll take less time and be far more efficient. Thank you anyways for your help help!

**Comment by smmmadden** [comment]
I got it working with the following changes to "both sides" and initial testing is looking good.  Got a lot more to test, but seems to be much happier. :-)
**com.google.gson.**Gson mainGSONBuilderVariable = new **com.google.gson.**GsonBuilder().setPrettyPrinting().create();

**Comment by Goldorion** [comment]
> I got it working with the following changes to "both sides" and initial testing is looking good. Got a lot more to test, but seems to be much happier. :-) com.google.gson.Gson mainGSONBuilderVariable = new com.google.gson.GsonBuilder().setPrettyPrinting().create();

Oh... I thought that was what you did.

**Comment by smmmadden** [comment]
I missed the left side of the equation so since nothing worked on the right, I thought I dig into google code to see some examples and found one that worked. :-)

**Comment by smmmadden** [comment]
one other thing I noticed is that the version listed in the file shows 5.8 when it should be 5.9 :-)
