### ISSUE TITLE
5.10 build issue when creating a config when the player joins the world

### ISSUE THREAD

**Issue by northwesttreesgaming** [Goldorion/File-Manager-MCreator#65]
### Issue description

Encountered a bug when trying to make a config when the player joins the world.
Simply won't compile and I have checked the plugin page for the example and everything is set up correctly.

### How to reproduce this issue?

Build Workspace, The issue will happen.

### Operating system

Windows

### Details

File Manager v5,10
MCreator 2024.1
NeoForge 1.20.4

### Example workspace

[workspace.zip](https://github.com/Goldorion/File-Manager-MCreator/files/15137250/workspace.zip)

### Logs

[file_manager_bug.txt](https://github.com/Goldorion/File-Manager-MCreator/files/15137252/file_manager_bug.txt)

### Issue tracker rule checks (please read carefully)

- [X] I have checked that my problem <a href='https://github.com/Goldorion/File-Manager-MCreator/issues?q=is%3Aissue' target='_blank'>is not already reported</a>
- [X] I have checked that my problem is not covered on <a href='https://mcreator.net/support/knowledgebase' target='_blank'>Knowledge Base</a> or on <a href='https://mcreator.net/wiki' target='_blank'>MCreator's Wiki</a>
- [X] I have checked that my written content does not violate the <a href='https://mcreator.net/wiki/general-publishing-guidelines' target='_blank'>publishing guidelines</a>

**Comment by Goldorion** [comment]
Closing the issue as you fixed it yourself as said on Discord.
