### ISSUE TITLE
MCreator gives a compilation error when I try to make a config

### ISSUE THREAD

**Issue by MargoxaTheGamer** [Goldorion/File-Manager-MCreator#7]
![bandicam 2021-04-14 11-56-06-224](https://user-images.githubusercontent.com/79755987/114685211-583c7600-9d1a-11eb-9859-db96f007d38b.jpg)

I have a problem, I made something like a config with your plugin, that should be created in game directory when player launches mc. It gave me a compilation error, so I thought, that I'm doing something wrong, so I tried to make a config exactly like in second screen, I created all the local variables and I used "When block broken" global trigger like in your screenshot...and it gave me a compilation error. I'm using MCreatorEAP20211b03117 and 3.0 version of your plugin and I'm on 1.16.4 generator. I guess, "THIS UPDATE IS NOT COMPATIBLE WITH THE LAST VERSIONS" means, that 3.0 will not be compatible with 2020.5, but will work on 03117 snapshot. Compilation error:

Executing 
    Gradle task: build

Build 
    info: MCreator 2021.1.03117 EAP (03117), forge-1.16.4, 64-bit, 12083 MB, 
    Windows 7, JVM 1.8.0_275, JAVA_HOME: D:\Mani 
    faili\Minecraft\MCcreator\MCreatorEAP20211b03117\jdk

> 
    Configure project :

New 
    Dep: net.minecraftforge:forge:1.16.4-35.1.4_mapped_snapshot_20201028-1.16.3

> 
    Task :compileJava

Note: 
    SpongePowered MIXIN Annotation Processor Version=0.8.2

Note: 
    ObfuscationServiceMCP supports type: "searge"

Note: 
    ObfuscationServiceMCP supports type: "notch"

C:\Users\Margita\MCreatorWorkspaces\bettermc\src\main\java\net\mcreator\bettermc\procedures\PlayerEntersTheGameProcedure.java:75: 
    error: variable obj is already defined in method executeProcedure(Map) 
    
 
               JsonObject obj = new Gson().fromJson(json, JsonObject.class);

 
                          ^

1 
    error

> 
    Task :compileJava FAILED

FAILURE: 
    Build failed with an exception.

* 
    What went wrong:

Execution 
    failed for task ':compileJava'.

> 
    Compilation failed; see the compiler error output for details.

* 
    Try:

Run 
    with --stacktrace option to get the stack trace. Run with --info or 
    --debug option to get more log output. Run with --scan to get full 
    insights.

* 
    Get more help at https://help.gradle.org

Deprecated 
    Gradle features were used in this build, making it incompatible with 
    Gradle 5.0.

Use 
    '--warning-mode all' to show the individual deprecation warnings.

See 
    https://docs.gradle.org/4.10.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD 
    FAILED in 4s

1 
    actionable task: 1 executed

BUILD 
    FAILED

Task 
    completed in 7 seconds

**Comment by Goldorion** [comment]
I already fixed the bug for the next version.
